version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile_php-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile_nginx
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - app-network
    volumes:
      - ./logs/nginx:/var/log/nginx

  elasticsearch:
    image: elasticsearch:7.17.21
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    networks:
      - app-network
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  filebeat:
    build:
      context: .
      dockerfile: ./Dockerfile_firebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/nginx:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - elasticsearch

networks:
  app-network:
    driver: bridge

volumes:
  grafana-storage: