name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push PHP-FPM image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_php-fpm
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/php-fpm:${{ github.sha }}

      - name: Build and push Nginx image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_nginx
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }}

      - name: Build and push Filebeat image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_firebeat
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/filebeat:${{ github.sha }}

      - name: Notify Telegram on Success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ Build and push succeeded for commit ${{ github.sha }}."

      - name: Notify Telegram on Failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="❌ Build and push failed for commit ${{ github.sha }}."
